### ISSUE TITLE
Update ulimits for root user processes with CloudFormation template

### ISSUE THREAD

**Issue by ybnelson** [yugabyte/aws-cloudformation#11]
Current install_software.sh sets ulimits for ec2-user and needs to be updated for root and persisted for reboots.

**Comment by kmuthukk** [comment]
has there been a discussion around whether we want the processes to run as root or ec2-user?

cc: @rkarthik007 , @vp15591 ?

**Comment by vp15591** [comment]
no @kmuthukk there was no such discussion.

**Comment by rkarthik007** [comment]
No, we have not discussed this. Ideally, we should create a new `yugabyte` user and run the process as that user, we should look into what that takes.

Till that happens, not sure which is easier:
* Running as root and changing the ulimits for the root user
* Running as ec2-user (guessing the ulimits here are good in our current template?)

cc @ramkumarvs @iSignal
